### ISSUE TITLE
configparser.py issue help please

### ISSUE THREAD

**Issue by lillois59** [amiryousefi/telegram-analysis#18]
Hi, How I can fix this issue ive used both python and Python3 (.6 .9) thanks
MACOSX high sierra python and dep update

(base) sofiane-MacBook-Pro:telegram-analysis Apple$ python3.6 ChannelUsers.py
Traceback (most recent call last):
  File "ChannelUsers.py", line 18, in <module>
    api_id = config['Telegram']['api_id']
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Telegram'

**Comment by lillois59** [comment]
solved

**Comment by sundaleek** [comment]
hello @lillois59 how did you fixed this issue?

**Comment by sundaleek** [comment]
hello @amiryousefi how to solve this?
`Traceback (most recent call last):
  File "/Users/david.ozmanyan/Downloads/telegram-analysis-master/ChannelMessages.py", line 31, in <module>
    api_id = config['Telegram']['api_id']
  File "/Users/david.ozmanyan/.pyenv/versions/3.9.10/lib/python3.9/configparser.py", line 963, in __getitem__
    raise KeyError(key)
KeyError: 'Telegram'
`

**Comment by lillois59** [comment]
hi @sundaleek

Get your Telegram API credentials
To connect to Telegram, we need an api_id and an api_hash. To get these parameters, you need to login to your Telegram core and go to the API development tools area. There is a form that you need to fill out, and after that, you can receive your api_id and api_hash.

Here’s Telegram’s help documentation about how to get your API credentials.
