### ISSUE TITLE
Error Found.

### ISSUE THREAD

**Issue by devendrachandora** [amiryousefi/telegram-analysis#5]
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.8.0 -- An enhanced Interactive Python.

runfile('C:/Users/Devendra Chandora/Downloads/telegram-analysis-master/telegram-analysis-master/ChannelMessages.py', wdir='C:/Users/Devendra Chandora/Downloads/telegram-analysis-master/telegram-analysis-master')
Traceback (most recent call last):

  File "<ipython-input-1-404fc4250568>", line 1, in <module>
    runfile('C:/Users/Devendra Chandora/Downloads/telegram-analysis-master/telegram-analysis-master/ChannelMessages.py', wdir='C:/Users/Devendra Chandora/Downloads/telegram-analysis-master/telegram-analysis-master')

  File "C:\Users\Devendra Chandora\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Devendra Chandora\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Devendra Chandora/Downloads/telegram-analysis-master/telegram-analysis-master/ChannelMessages.py", line 95, in <module>
    with client:

  File "C:\Users\Devendra Chandora\Anaconda3\lib\site-packages\telethon\helpers.py", line 151, in _sync_enter
    'You must use "async with" if the event loop '

RuntimeError: You must use "async with" if the event loop is running (i.e. you are inside an "async def")

**Comment by bufemc** [comment]
I am not the author but this seems not to be related to this project. Maybe some kind of issue with Anaconda3 and Telethon. Did you update both to latest versions? I recently runned this project here myself, works fine, but just used PyCharm community edition.

**Comment by mathu619** [comment]
As bufemc pointed out the code works in pycharm but it throws error in Anaconda

**Comment by amiryousefi** [comment]
Ok, this one is a bit old but for anybody else who may face the same problem:
Make sure to use latest code and the proper version of Telethon in Anaconda. Recently I checked the source code and created a video tutorial for it, it might help: https://www.youtube.com/watch?v=aU1p-F7gDo4&ab_channel=AmirYousefi
